name: Build and Push to Cachix
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['Update Inputs']
    types: [completed]
    branches:
      - main

jobs:
  publish:
    name: Publish Flake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, aarch64]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@V27

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v15
      with:
        name: adtya
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build nix flake
      run: nix build -L .#caddy

